src/objects/Cash_Withdrawal__c.object
<CustomObject>
    <label>Cash Withdrawal</label>
    <nameField>
        <label>Cash Withdrawal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Withdrawals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Withdrawal_Sum__c</fullName>
        <label>Cash Withdrawal Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Withdrawal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cash Withdrawal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shopping</fullName>
                </value>
                <value>
                    <fullName>Groceries</fullName>
                </value>
                <value>
                    <fullName>Bills</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                    <label>Cash Payment</label>
                </value>
                <value>
                    <fullName>Credit Payment</fullName>
                </value>
                <value>
                    <fullName>Various</fullName>
                </value>
                <value>
                    <fullName>Cash Withdrawal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cashExpenseUpdate.cls
public with sharing class cashExpenseUpdate{
    public static void updateDescriptions (List <Expense__c> expenses) {
        for(Expense__c aExpense : expenses) {
            if (aExpense.Category__c == 'Cash Payment') {
                aExpense.Description_Test__c = 'Amount to be deducted from Cash Withdrawal Sum';   
            } else if (aExpense.Cash_Withdrawal__c == true) {
                aExpense.Amount__c = aExpense.Cash_Withdrawal_Sum__c + aExpense.Amount__c;
            }  
        }
    }

}